#!/usr/bin/env bash
# Transfer a file to a remote server's home directory using SCP and SSH key authentication

# Check if the number of arguments is less than 4
if [ "$#" -lt 4]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file, disable strict host key checking
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"